app/django_movies/django_movies/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include


urlpatterns = [
    path('', include('movie.views.home.urls')),
    path('admin/', admin.site.urls),
    path('home/',include('movie.views.home.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/django_movies/movie/views/home/urls.py
from django.urls import path

from .views import Home, Details, Search

app_name = 'movies'

urlpatterns = [
    path('', Home, name='Home'),
    path('Search', Search, name='Search'),
    path('Views/<int:movies_id>', Details, name='Details')
]

app/django_movies/movie/models/genresModels.py
from django.db import models

class GenresModels(models.Model):
    genres_id = models.AutoField(primary_key=True)
    GenresName = models.TextField(max_length=150,blank=True, null=True)
    
    def __str__(self):
        return self.GenresName

app/django_movies/movie/models/moviesModels.py
from django.db import models
from .genresModels import GenresModels
from .mpaaratingModels import MpaaRatingsModels

class MoviesModels(models.Model):
    movies_id = models.AutoField(primary_key=True)
    moviesName = models.CharField(max_length=150,blank=True,unique=True)
    moviesDescription = models.TextField(max_length=150,blank=True,null=True)
    moviesFiles = models.FileField(upload_to='movies/')
    moviesImg = models.ImageField(upload_to='preview_images/')
    moviesDuration = models.IntegerField(max_length=10)
    moviesLanguage = models.TextField(blank=True,null=True)
    moviesUserRatings = models.FloatField(default=0.00)
    moviesGenres = models.ForeignKey(GenresModels, on_delete=models.CASCADE)
    moviesMpaaRating = models.ForeignKey(MpaaRatingsModels, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.moviesName

    

app/django_movies/movie/models/mpaaratingModels.py
from django.db import models

class MpaaRatingsModels(models.Model):
    mpaaRatting_id = models.AutoField(primary_key=True)
    MpaaType = models.CharField(max_length=150,blank=True,null=True)
    MpaaLabel = models.CharField(max_length=150,blank=True,null=True)
    
    def __str__(self):
        return self.MpaaLabel

app/django_movies/movie/views/home/forms.py
from django import forms

class SearchMovieForms(forms.Form):
    movie_name = forms.CharField(label="Movies Name",max_length=255)

app/django_movies/movie/views/home/views.py
from django.shortcuts import redirect, render
from django.http import Http404

from movie.models.moviesModels import MoviesModels

from .forms import SearchMovieForms

def Home(request):
    movies = MoviesModels.objects.all()
    context = {
        "movies":movies
    }

    return render(request,'home/index.html',context)

def Details(request,movies_id):
    try:
        movies = MoviesModels.objects.get(pk=movies_id)
        context = {
            "movies":movies
        }
    except MoviesModels.DoesNotExist:
        raise Http404("Movies Not Found")
    
    return render(request,'home/details.html',context)

def Search(request):
    if request.method == 'POST':
        form = SearchMovieForms(request.POST)
        if form.is_valid():
            movies_name = form.cleaned_data['movie_name']
            results = MoviesModels.objects.filter(moviesName__icontains='{s}'.format(s=movies_name))
            context = {
                "results":results,
                "form":form
            }
            return render(request,'home/results.html',context)
    else:
        form = SearchMovieForms()
        results = MoviesModels.objects.all()
        context = {
            "results":results,
            "form":form
        }
        return render(request,'home/results.html', context)

app/django_movies/templates/home/details.html
{% extends "layouts.html" %}
    {% block content %}
        <h1>Detail Movies</h1>
        <div>
            <a href="{% url 'movies:Home' %}" class="btn btn-success">Back</a>
        </div>

        <br>

        <div>
            <h2>{{ movies.moviesName }}</h2>
            <img src="../media/{{ movies.moviesFiles  }}" width="250px" height="250px" />
            <h4>
                <span class="badge badge-warning">{{ movies.moviesDuration }}</span>
                <span class="badge badge-success">{{ movies.moviesUserRatings }}</span>
                <span class="badge badge-info">{{ movies.moviesLanguage }}</span>
            </h4>

            <p>
                {{ movies.moviesDescription }}
            </p>
        </div>
    {% endblock %}

app/django_movies/templates/home/index.html
{% extends "layouts.html" %}
    {% block content %}
    <a href="{% url 'movies:Search' %}" class="btn btn-primary">Search</a>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Movie Name</th>
                <th>Image</th>
                <th>Language</th>
                <th>Duration</th>
                <th>Desc Movie</th>
                <th>User Rating</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% if movies %}
                {% for movie in movies %}
                <tr>
                    <td>
                        <p> Movie Name {{ movie.moviesName  }}</p>
                        <p> Mpa Rating {{ movie.moviesMpaaRating.MpaaLabel }}</p>
                        <p> Genres {{ movie.moviesGenres.GenresName }}</p>
                    </td>
                    <td><img src="media/{{ movie.moviesFiles  }}" width="150px" height="150px" /></td>
                    <td>{{ movie.moviesLanguage  }}</td>
                    <td>{{ movie.moviesDuration  }}</td>
                    <td>{{ movie.moviesDescription  }}</td>
                    <td>{{ movie.moviesUserRatings  }}</td>
                    <td>
                        <a href="{% url 'movies:Details' movie.movies_id %}" class="btn btn-primary">Views</a>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="8"> Data Not Found</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    {% endblock %}

app/django_movies/templates/home/results.html
{% extends "layouts.html" %}
    {% block content %}
<h1>Movies Search</h1>
<div>
  <a href="{% url 'movies:Home' %}" class="btn btn-success">Back</a>
</div>
<br>
<div>
<form action="{% url 'movies:Search' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Movie Name</th>
            <th>Image</th>
            <th>Language</th>
            <th>Duration</th>
            <th>Desc Movie</th>
            <th>User Rating</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% if results %}
            {% for movie in results %}
            <tr>
                <td>{{ movie.moviesName  }}</td>
                <td><img src="media/{{ movie.moviesFiles  }}" width="150px" height="150px" /></td>
                <td>{{ movie.moviesLanguage  }}</td>
                <td>{{ movie.moviesDuration  }}</td>
                <td>{{ movie.moviesDescription  }}</td>
                <td>{{ movie.moviesUserRatings  }}</td>
                <td>
                    <a href="{% url 'movies:Details' movie.movies_id %}" class="btn btn-primary">Views</a>
                    <a href="" class="btn btn-success">Mpa Ratting</a>
                    <a href="" class="btn btn-info">Genres</a></td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="8"> Data Not Found</td>
            </tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}

app/django_movies/templates/layouts.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Movies List</title>
    {% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  </head>
  <body>
        {% block content %}{% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% load static  %}
        <script src="{% static 'js/bootstrap.js' %}"></script>
        {% block javascript %}{% endblock javascript %}
  </body>
</html>